name=input("Digite o nome do cliente:")
dia=input("Digite o dia de vencimento:")
mes=input("Digite o mês de vencimento:")
val=input("Digite o valor da fatura:")
print("Ola,",name)
print("A sua fatura com vencimento em",dia,"de",mes,"no valor de R$",val,"está fechada.")